// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from main.go:

func InitService() (*Service, error) {
	repo := NewUserRepo()
	cache := NewUserCache()
	companyAPI := NewCompanyAPI()
	publisher := NewPublisher()
	service := NewService(repo, cache, companyAPI, publisher)
	return service, nil
}

// main.go:

type Service struct {
	userRepo       Repo
	userCache      Cache
	companyAPI     CompanyAPI
	eventPublisher Publisher
}

var svcSet = wire.NewSet(
	NewUserRepo,
	NewUserCache,
	NewCompanyAPI,
	NewPublisher,
)

func NewService(
	userRepo Repo,
	userCache Cache,
	companyAPI CompanyAPI,
	eventPublisher Publisher,
) *Service {
	return &Service{
		userRepo:       userRepo,
		userCache:      userCache,
		companyAPI:     companyAPI,
		eventPublisher: eventPublisher,
	}
}
